version: '3.8'

services:
  django_app:
    build:
      context: ./django_project
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./django_project:/django_project
    working_dir: /django_project
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_NAME=django_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  my_db:
    image: mysql:8.0
    container_name: my_db
    restart: always
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 30s
      timeout: 10s
      retries: 3
